version: '3.8'

services:
  rasa:
    image: duggireddypoojitha/rasa-rasa:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./endpoints.yml:/app/endpoints.yml
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - action_server
      - mysql
    networks:
      - rasa_network  # Declare a network for communication between services

  action_server:
    image: duggireddypoojitha/rasa-action_server:latest
    build:
      context: ./actions
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    depends_on:
      - mysql
    networks:
      - rasa_network  # Use the same network as rasa service

  flask_server:
    image: duggireddypoojitha/rasa-flask_server:latest
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rasa
    networks:
      - rasa_network  # Use the same network as rasa service
  mysql:
    image: mysql
    container_name: dev-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - rasa_network

  phpmyadmin:
    image: phpmyadmin
    container_name: dev-phpmyadmin
    environment:
      PMA_HOST: dev-mysql
    ports:
      - "3306:80"
    depends_on:
      - mysql
    networks:
      - rasa_network
networks:
  rasa_network:  # Define a custom bridge network for Rasa services
    driver: bridge
